global:
  scrape_interval: 15s

scrape_configs:
  - job_name: edms-api
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8000"]

  - job_name: celery-flower
    static_configs:
      - targets: ["flower:5555"]
